name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 3: Build Docker image
      - name: Build Docker image
        run: docker build -t shraddhaskumar/app:latest .

      # Step 4: Push Docker image
      - name: Push Docker image
        run: docker push shraddhaskumar/app:latest

      # Step 5: Scan Docker image with Trivy
      - name: Scan Docker image
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: shraddhaskumar/app:latest
          format: table
          exit-code: 1   # fail workflow if vulnerabilities found